Sil - Compatibiliteit
Programmeerclub-WLG/Agenda-App pull request #8
Opened 2017-06-08 14:15 UTC by silvanzoest

Checkt of nodige keys aanwezig zijn in gegeven dictionary.
Nog gebeuren: Checken of waarden keys overeenkomt met benodigde waarden.

2017-06-08 16:14 UTC, jmaarleveld requested changes
Je hebt al een goed begin gemaakt en aan je pogingen is te zien dat je al een redelijk brede kennis hebt van de syntax van Python.

Het probleem is dat je echter nog niet precies weet wat alles doet en dat je nog niet alle vaardigheden onder de knie hebt.

De opdrachten die ik in de review heb neergezet zullen je helpen de code beter te begrijpen en vormen een redelijk goede voorbereiding voor de code die je nog moet schrijven om de functie af te maken.

De code die je tot nu toe hebt is misschien niet veel maar het is wel correct en bug-proof.

Ga dus zo door en je komt er wel!

PS.
Je functie checkt nu of alle keys die zich in de dictionary moeten bevinden ook daadwerkelijk aanwezig zijn. Probeer als oefening eens een extra check toe te voegen om zeker te zijn dat er geen extra overbodige keys in de dictionary aanwezig zijn.

2017-06-08 16:14 UTC, jmaarleveld commented on backend/compat.py
> +    KeyList = ['title', 'description', ...]
Niet vergeten de lijst af te maken he :P

2017-06-08 16:14 UTC, kolokkol commented on backend/compat.py
> +    for key in KeyList:
De `for` loop ging wat stroef. Het is waarschijnlijk handig als je eens kijkt op codecedemy.

Daarnaast zou ik graag willen dat je de volgende vragen maakt:
- De algemene syntax van de `for`-loop is `for x in y`. Wat is `x`? En wat stelt `y` voor?
- Wat doet `range`?
- Wat doet `enumerate`?
- Wat doet `for key in {1: 2, 3: 4}: print(key)`?
- Hoe zou je de values in de dictionary van de vorige vraag printen?
- Wat doet `for item in [1, 2, 3, 4]: print(item)`?

Je kunt de vragen wel maken in een apart bestand en dat uploaden (help ik wel even mee).

2017-06-08 16:14 UTC, kolokkol commented on backend/compat.py
> +        if key not in dict:
De `item in iterable` syntax checkt of een item onderdeel is van een collectie/iterables met data.

De `key in dictionary` syntax checkt of de `key` zich in de `dict` bevindt. Hoe zou je checken of een bepaalde variabele zich bevindt in de `values` van de dictionary? Hoe doe je dit met de `in` syntax?

2017-06-08 16:14 UTC, kolokkol commented on backend/compat.py
> +            continue
Als een `for`-loop zijn 'body' (ingesprongen deel) heeft uitgevoerd gaat hij terug naar het begin van de loop zolang er nog items zijn om overt te itereren. Wat betekent dit voor deze `continue`?

2017-06-14 07:27 UTC, kolokkol commented on backend/compat.py
> +        if key not in dict:
Hier staat trouwens `key not in dict`. De syntax `def validate_appointment(data: dict)` betekent dat de naam/variabele `data` `type` `dict` zou moeten zijn. De variabele naam is dus `data` dus je moet `dict` even vervangen door `data`

2017-06-14 07:52 UTC, silvanzoest commented on backend/compat.py
> +    for key in KeyList:
- X stelt één key uit de dictionary voor en y is die list. Dus zolang er nog een key in de dictionary zit die de loop nog niet gehad heeft gaat de loop door.
- Range genereerd nummers en daardoor kun je hem gebruiken voor loops.
- Enumerate geeft elke variabele uit een list een waarde beginnend bij 0.
- hij print de keys namelijk 1 en 3, de 2 en 4 zijn de values.
- 'for value in {1: 2, 3: 4}: print(value)'.
-  Hij print de waardes 1 2 3 en 4, deze items zitten in een list en hiervoor zaten de keys met values in een dictionary.(zit dus verschil tussen)

2017-06-14 08:00 UTC, kolokkol commented on backend/compat.py
> +    for key in KeyList:
> X stelt één key uit de dictionary voor en y is die list. Dus zolang er nog een key in de dictionary zit die de loop nog niet gehad heeft gaat de loop door.

Voor het geval van de dictionary klopt dit inderdaad. Bekijk het echter eens algemener: Een for loop kan over veel meer verschillende dingen loopen, bijvoorbeeld ook een `list`

> Range genereerd nummers en daardoor kun je hem gebruiken voor loops.

Ja. Wat is er speciaal aan de manier waarop range nummers genereert?

> Enumerate geeft elke variabele uit een list een waarde beginnend bij 0.

Kun je een voorbeeld geven van hoe je enumerate zou gebruiken in een voorbeeld?

> hij print de keys namelijk 1 en 3, de 2 en 4 zijn de values.

Klopt

> 'for value in {1: 2, 3: 4}: print(value)'

Dit klopt niet. `for key in dict` loopt altijd over de keys, ongeacht de naam van de variabele in de for-loop.

> Hij print de waardes 1 2 3 en 4, deze items zitten in een list en hiervoor zaten de keys met values in een dictionary.(zit dus verschil tussen)

close enough

2017-06-15 05:13 UTC, kolokkol commented
Vervangen door nieuwe pull request.

closed.

2017-06-15 05:13 UTC, closed without merging